// src/app/about/about.component.ts
// Imports
import { Component, OnInit } from '@angular/core';

// Component
@Component({
    selector: 'app-about',
    templateUrl: './about.component.html',
    styleUrls: ['./about.component.scss'],
})
export class AboutComponent implements OnInit {
    constructor() {}

    ngOnInit(): void {}
}

<article class="portfolio-about">
    <div class="row">
        <div class="col-12 col-md-8">
            <img
                class="img-fluid rounded"
                src="/assets/images/profile.jpg"
                alt="Profile Image"
            />
            <h1 class="display-4">Zack Mowrer</h1>
            <p class="lead text-dark">
                The Full-Stack Child Prodigy from the Mountain State
            </p>
            <p class="bio">
                Having been one of the original members of the
                <a
                    href="https://wvcoding.org"
                    target="_blank"
                    rel="noopener noreferer"
                >
                    West Virginia Coding Club
                </a>
                since its founding in late 2016, I have been working in
                Full-Stack JavaScript since 2017; furthermore, I am willing to
                adapt to the needs of others and learn new technologies as
                needed. Unit testing (particularly with Jest) and code
                formatting tools (such as ESLint and Prettier) are nothing new
                for me.
            </p>
            <p>
                <em>Oh, and did I mention that I am only 16?</em>
            </p>
        </div>
        <div class="col-12 col-md-4">
            <h6>Skills</h6>
            <ul>
                <li>HTML</li>
                <li>CSS</li>
                <li>JavaScript</li>
                <li>jQuery</li>
                <li>AJAX</li>
                <li>Node.js</li>
                <li>Express</li>
                <li>React</li>
                <li>React Router</li>
            </ul>
            <h6>Credentials</h6>
            <img
                class="img-fluid"
                src="https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/13232229"
            />
            <h6>Contact Info</h6>
            <ul>
                <li>
                    <a
                        href="mailto:Zackmowrer@gmail.com"
                        target="_blank"
                        rel="noopener noreferer"
                    >
                        Zackmowrer@gmail.com
                    </a>
                </li>
            </ul>
            <a
                class="btn btn-dark btn-block"
                href="https://www.linkedin.com/in/zack-mowrer-39902b18b/"
                target="_blank"
                rel="noopener noreferer"
            >
                LinkedIn
            </a>
            <a
                class="btn btn-dark btn-block"
                href="https://twitter.com/zackmowrer"
                target="_blank"
                rel="noopener noreferer"
            >
                GitHub
            </a>
            <a
                class="btn btn-dark btn-block"
                href="https://github.com/ZTMowrer947"
                target="_blank"
                rel="noopener noreferer"
            >
                Twitter
            </a>
        </div>
    </div>
</article>

// src/pages/about.tsx
// Imports
import React from 'react';
import ButtonGroup from 'react-bootstrap/ButtonGroup';
import Col from 'react-bootstrap/Col';
import Image from 'react-bootstrap/Image';
import Row from 'react-bootstrap/Row';

// Component
const AboutPage: React.FC = () => {
    return (
        <article className="portfolio-about mt-3">
            <Row>
                <Col xs={12} md={8}>
                    <Image src="/images/profile.jpg" alt="Profile Image" fluid rounded />
                    <h1 className="display-4">Zack Mowrer</h1>
                    <p className="lead text-dark">The Mountain State Programming Prodidy</p>
                    <p>
                        Having been programming seriously since late 2016, I have developed into a lifelong learner with a burning passion
                        to write software that makes others happy. I am hard-working, honest person above all else, always looking for
                        something to learn or another challenge to overcome. A tinkerer and experimenter at heart, I am more than willing to
                        adapt to new technologies and to the needs of others.
                    </p>
                    <p>
                        I also have the certification to back up my programming prowess, being the first and youngest person in West
                        Virginia to complete the Treehouse Techdegree Program, and the second youngest to do so in the entire world.
                    </p>
                    <p>
                        <em>Did I mention that I am only 16?</em>
                    </p>
                </Col>
                <Col xs={12} md={4}>
                    <h6>Skills</h6>
                    <ul>
                        <li>HTML</li>
                        <li>CSS</li>
                        <li>JavaScript</li>
                        <li>TypeScript</li>
                        <li>jQuery</li>
                        <li>AJAX</li>
                        <li>Node.js</li>
                        <li>Express</li>
                        <li>React</li>
                    </ul>
                    <ButtonGroup className="w-100 mb-3">
                        <a
                            className="btn btn-dark"
                            href="https://www.linkedin.com/in/zack-mowrer-39902b18b/"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            LinkedIn
                        </a>
                        <a className="btn btn-dark" href="https://twitter.com/zackmowrer" target="_blank" rel="noopener noreferrer">
                            Twitter
                        </a>
                        <a className="btn btn-dark" href="https://github.com/ZTMowrer947" target="_blank" rel="noopener noreferrer">
                            GitHub
                        </a>
                    </ButtonGroup>
                </Col>
            </Row>
        </article>
    );
};

// Exports
export default AboutPage;
